import * as z from "zod";

/**
 * The HTTP bodies this application's own endpoints speak.
 *
 * @remarks
 * In `src/core/` rather than beside the handler that answers with them,
 * because both ends of the wire need the same shape: the handler validates the
 * request with it, and the browser code that will call the endpoint parses the
 * answer with it. A schema that lived in `src/server/` would be unreachable
 * from the client half without inverting the import order.
 *
 * These are *our* schemas, validated by zod on this side of the wire. A schema
 * a model's structured output is asked for belongs with the prompt that asks
 * for it, under `src/server/prompts/` — except for a piece both sides need,
 * which are split into focused modules so the question, score, and dashboard
 * contracts can each grow without making one file carry unrelated ceilings.
 */

/**
 * The most questions one batch may ask for.
 *
 * @remarks
 * A ceiling on what one request can spend: every question in a batch is
 * generated by the same model call, so the number bounds both the answer's
 * size and its cost. Ten is well under the number of distinct scenario seeds
 * `drawSeeds` can produce, so a legal `count` is always drawable.
 */
export const MAX_QUESTIONS_PER_BATCH = 10;

/** The JSON body `POST /api/questions` accepts. */
export const questionsRequestSchema = z.object({
  /** How many questions to generate, bounded at both ends. */
  count: z.int().min(1).max(MAX_QUESTIONS_PER_BATCH),
});

/** The seed one question was generated from, by id rather than by label. */
const wireSeed = z.object({
  interlocutorId: z.string(),
  settingId: z.string(),
  topicId: z.string(),
});

/**
 * One generated question as a client receives it.
 *
 * @remarks
 * `id` is assigned by the server, not by the model: it is what a later answer
 * and its score are keyed by, so it has to be unique whatever the model wrote.
 * `seed` carries ids rather than labels because a client that needs the words
 * has them in `scenarioLine` already, and an id is what a stored answer can be
 * analysed by later.
 */
const wireQuestion = z.object({
  id: z.string(),
  question: z.string(),
  scenarioLine: z.string(),
  seed: wireSeed,
});

/** The JSON body `POST /api/questions` answers with. */
export const questionsResponseSchema = z.object({
  questions: z.array(wireQuestion),
});

/** The request body {@link questionsRequestSchema} accepts. */
export type QuestionsRequest = z.infer<typeof questionsRequestSchema>;

/** The answer body {@link questionsResponseSchema} describes. */
export type QuestionsResponse = z.infer<typeof questionsResponseSchema>;

/** One question on the wire. */
export type WireQuestion = z.infer<typeof wireQuestion>;

export {
  MAX_SCORE_ANSWER_LENGTH,
  MAX_SCORE_QUESTION_LENGTH,
  MAX_SCORE_SCENARIO_LINE_LENGTH,
  scoreCommentsSchema,
  scoreItemsSchema,
  scoreRequestSchema,
  scoreResponseSchema,
} from "./wire-score";
export type { ScoreRequest, ScoreResponse } from "./wire-score";

/**
 * `POST /api/dashboard`'s wire contract.
 *
 * @remarks
 * Declared in `src/core/wire-dashboard.ts`, a separate module, and re-exported
 * here under this module's name: this endpoint's own per-field ceilings would
 * have pushed this file over `eslint.config.mjs`'s 200-line `max-lines`
 * budget, and `writing-typescript` calls a module that outgrows that budget
 * "a module doing more than one thing" — split it rather than raise the
 * number. A caller still writes `from "../../core/wire"` either way.
 */
export {
  dashboardRequestSchema,
  dashboardResponseSchema,
  MAX_DASHBOARD_ANSWER_LENGTH,
  MAX_DASHBOARD_COMMENT_LENGTH,
  MAX_DASHBOARD_QUESTION_LENGTH,
  MAX_DASHBOARD_RECORDED_AT_LENGTH,
  MAX_DASHBOARD_RECORDS,
  MAX_DASHBOARD_RUBRIC_VERSION_LENGTH,
  MAX_DASHBOARD_SCENARIO_LINE_LENGTH,
  type DashboardRecord,
  type DashboardRequest,
  type DashboardResponse,
} from "./wire-dashboard";
