import * as z from "zod";

import {
  CRITERIA,
  ITEM_IDS,
  SCORE_LEVELS,
  type CriterionId,
  type ItemId,
} from "./rubric";

/**
 * The HTTP bodies this application's own endpoints speak.
 *
 * @remarks
 * In `src/core/` rather than beside the handler that answers with them,
 * because both ends of the wire need the same shape: the handler validates the
 * request with it, and the browser code that will call the endpoint parses the
 * answer with it. A schema that lived in `src/server/` would be unreachable
 * from the client half without inverting the import order.
 *
 * These are *our* schemas, validated by zod on this side of the wire. A schema
 * a model's structured output is asked for belongs with the prompt that asks
 * for it, under `src/server/prompts/` — except for a piece both sides need,
 * which is here so the two cannot drift: {@link scoreItemsSchema} and
 * {@link scoreCommentsSchema} are what the grader is asked for *and* what the
 * answer carries, and `src/server/prompts/scoring.ts` imports them rather than
 * declaring a second copy `core` could not see.
 */

/**
 * The most questions one batch may ask for.
 *
 * @remarks
 * A ceiling on what one request can spend: every question in a batch is
 * generated by the same model call, so the number bounds both the answer's
 * size and its cost. Ten is well under the number of distinct scenario seeds
 * `drawSeeds` can produce, so a legal `count` is always drawable.
 */
export const MAX_QUESTIONS_PER_BATCH = 10;

/** The JSON body `POST /api/questions` accepts. */
export const questionsRequestSchema = z.object({
  /** How many questions to generate, bounded at both ends. */
  count: z.int().min(1).max(MAX_QUESTIONS_PER_BATCH),
});

/** The seed one question was generated from, by id rather than by label. */
const wireSeed = z.object({
  interlocutorId: z.string(),
  settingId: z.string(),
  topicId: z.string(),
});

/**
 * One generated question as a client receives it.
 *
 * @remarks
 * `id` is assigned by the server, not by the model: it is what a later answer
 * and its score are keyed by, so it has to be unique whatever the model wrote.
 * `seed` carries ids rather than labels because a client that needs the words
 * has them in `scenarioLine` already, and an id is what a stored answer can be
 * analysed by later.
 */
const wireQuestion = z.object({
  id: z.string(),
  question: z.string(),
  scenarioLine: z.string(),
  seed: wireSeed,
});

/** The JSON body `POST /api/questions` answers with. */
export const questionsResponseSchema = z.object({
  questions: z.array(wireQuestion),
});

/** The request body {@link questionsRequestSchema} accepts. */
export type QuestionsRequest = z.infer<typeof questionsRequestSchema>;

/** The answer body {@link questionsResponseSchema} describes. */
export type QuestionsResponse = z.infer<typeof questionsResponseSchema>;

/** One question on the wire. */
export type WireQuestion = z.infer<typeof wireQuestion>;

/**
 * The ceilings `POST /api/score` accepts, in characters once trimmed.
 *
 * @remarks
 * Each one bounds the input tokens a single grading call can be billed for,
 * and each is sized to what the screen actually sends: a generated question
 * and its one-line scenario caption, and a reply the drill asks for in one or
 * two sentences. Raising one is a cost decision, not a formality.
 */
export const MAX_SCORE_QUESTION_LENGTH = 300;

/** @see {@link MAX_SCORE_QUESTION_LENGTH} */
export const MAX_SCORE_SCENARIO_LINE_LENGTH = 200;

/** @see {@link MAX_SCORE_QUESTION_LENGTH} */
export const MAX_SCORE_ANSWER_LENGTH = 600;

/**
 * The JSON body `POST /api/score` accepts.
 *
 * @remarks
 * How long the learner took, and whether the timer submitted for them, are
 * deliberately absent: the grader must not know either, because a reply is
 * graded on what it says and nothing else, and the client already holds the
 * timing for the record it keeps. `scenarioLine` has a ceiling but no floor —
 * a question drawn without a caption is legal, an empty reply is not.
 */
export const scoreRequestSchema = z.object({
  question: z.string().trim().min(1).max(MAX_SCORE_QUESTION_LENGTH),
  scenarioLine: z.string().trim().max(MAX_SCORE_SCENARIO_LINE_LENGTH),
  answer: z.string().trim().min(1).max(MAX_SCORE_ANSWER_LENGTH),
});

/** One item's verdict: the reasoning first, then the level it justifies. */
const scoreItem = z.object({
  rationale: z.string(),
  // `z.literal` of the six levels converts to a numeric `enum`, which the
  // provider's strict JSON Schema mode accepts. A `.min()`/`.max()` pair would
  // rely on `minimum`/`maximum`, which strict mode does not guarantee.
  score: z.literal([...SCORE_LEVELS]),
});

/**
 * The eight item results, keyed by {@link ITEM_IDS} in rubric order.
 *
 * @remarks
 * Built from the rubric rather than retyped, so an item added there cannot be
 * left out of what the model is asked for. The assertion restates only what
 * `ITEM_IDS` already guarantees — it is `readonly ItemId[]` covering the whole
 * union — and the scoring suite pins both the key set and its order.
 */
export const scoreItemsSchema = z.object(
  Object.fromEntries(ITEM_IDS.map((id) => [id, scoreItem])) as Record<
    ItemId,
    typeof scoreItem
  >,
);

/** One comment per criterion, keyed by {@link CRITERIA} in rubric order. */
export const scoreCommentsSchema = z.object(
  Object.fromEntries(CRITERIA.map((criterion) => [criterion.id, z.string()])) as Record<
    CriterionId,
    z.ZodString
  >,
);

/**
 * The JSON body `POST /api/score` answers with.
 *
 * @remarks
 * `rubricVersion` and `model` are the server's, never the caller's: a stored
 * score is comparable to another only when both were graded under the same
 * rubric by the same model, so the answer records what actually scored the
 * reply rather than what a client assumed.
 */
export const scoreResponseSchema = z.object({
  rubricVersion: z.string(),
  model: z.object({ alias: z.string(), reasoningEffort: z.string() }),
  items: scoreItemsSchema,
  comments: scoreCommentsSchema,
  modelReply: z.string(),
});

/** The request body {@link scoreRequestSchema} accepts. */
export type ScoreRequest = z.infer<typeof scoreRequestSchema>;

/** The answer body {@link scoreResponseSchema} describes. */
export type ScoreResponse = z.infer<typeof scoreResponseSchema>;

/** The most records one `POST /api/dashboard` call may summarise. */
export const MAX_DASHBOARD_RECORDS = 10;
/** A `DrillRecord`, trimmed to what the dashboard's trend paragraph is written from. */
export const dashboardRecordSchema = z.object({
  recordedAt: z.string(),
  question: z.object({ text: z.string(), scenarioLine: z.string() }),
  answer: z.string(),
  scores: z.record(z.enum(ITEM_IDS), z.literal([...SCORE_LEVELS])),
  comments: scoreCommentsSchema,
  rubricVersion: z.string(),
});
/** One record as {@link dashboardRequestSchema} accepts it. */
export type DashboardRecord = z.infer<typeof dashboardRecordSchema>;
/** Refused with 400 when the records mix `rubricVersion`, which the client filters to one before sending. */
export const dashboardRequestSchema = z
  .object({ records: z.array(dashboardRecordSchema).min(1).max(MAX_DASHBOARD_RECORDS) })
  .refine(
    (value) => new Set(value.records.map((record) => record.rubricVersion)).size === 1,
    { message: "Every record must share the same rubricVersion.", path: ["records"] },
  );
/** The JSON body `POST /api/dashboard` answers with. */
export const dashboardResponseSchema = z.object({ summary: z.string() });
/** The request body {@link dashboardRequestSchema} accepts. */
export type DashboardRequest = z.infer<typeof dashboardRequestSchema>;
/** The answer body {@link dashboardResponseSchema} describes. */
export type DashboardResponse = z.infer<typeof dashboardResponseSchema>;
